# Generated by Django 4.2.10 on 2024-02-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="socialmediapost", name="user",),
    ]
